# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all()
daniel = User.create(email: 'daniel@ga.co', password: 'chicken', password_confirmation: 'chicken', admin: false)
chris = User.create(email: 'chris@ga.co', password: 'chicken', password_confirmation: 'chicken', admin: false)
harrison = User.create(email: 'harrison@ga.co', password: 'chicken', password_confirmation: 'chicken', admin: false)
badger = User.create(email: 'badger@ga.co', password: 'chicken', password_confirmation: 'chicken', admin: false)
admin = User.create(email: 'admin@ga.co', password: 'chicken', password_confirmation: 'chicken', admin: true)


Airplane.destroy_all()
first_plane = Airplane.create(name: 'Boeing 737', columns: 4, rows: 30)
second_plane = Airplane.create(name: 'Boeing 747', columns: 6, rows: 40)
third_plane = Airplane.create(name: 'Boeing 787', columns: 5, rows: 35)
fourth_plane = Airplane.create(name: 'Airbus A380', columns: 7, rows: 40)

Flight.destroy_all()
flight_111 = Flight.create(flight_number: 111, origin: 'SYD', destination: 'LAX', date: DateTime.new(2016,4,19), airplane_id: first_plane.id)
flight_222 = Flight.create(flight_number: 222, origin: 'LAX', destination: 'SYD', date: DateTime.new(2016,4,20), airplane_id: first_plane.id)
flight_333 = Flight.create(flight_number: 333, origin: 'LAX', destination: 'LHR', date: DateTime.new(2016,4,20), airplane_id: second_plane.id)
flight_444 = Flight.create(flight_number: 444, origin: 'LHR', destination: 'LAX', date: DateTime.new(2016,4,21), airplane_id: second_plane.id)
flight_555 = Flight.create(flight_number: 555, origin: 'JFK', destination: 'CDG', date: DateTime.new(2016,4,23), airplane_id: third_plane.id)
flight_666 = Flight.create(flight_number: 666, origin: 'CDG', destination: 'JFK', date: DateTime.new(2016,4,24), airplane_id: third_plane.id)
flight_777 = Flight.create(flight_number: 777, origin: 'HKG', destination: 'SYD', date: DateTime.new(2016,4,27), airplane_id: fourth_plane.id)
flight_888 = Flight.create(flight_number: 888, origin: 'SYD', destination: 'HKG', date: DateTime.new(2016,4,28), airplane_id: fourth_plane.id)
flight_211 = Flight.create(flight_number: 211, origin: 'SYD', destination: 'LAX', date: DateTime.new(2016,6,19), airplane_id: first_plane.id)
flight_322 = Flight.create(flight_number: 322, origin: 'LAX', destination: 'SYD', date: DateTime.new(2016,6,20), airplane_id: first_plane.id)
flight_433 = Flight.create(flight_number: 433, origin: 'LAX', destination: 'LHR', date: DateTime.new(2016,6,20), airplane_id: second_plane.id)
flight_544 = Flight.create(flight_number: 544, origin: 'LHR', destination: 'LAX', date: DateTime.new(2016,6,21), airplane_id: second_plane.id)
flight_655 = Flight.create(flight_number: 655, origin: 'JFK', destination: 'CDG', date: DateTime.new(2016,6,23), airplane_id: third_plane.id)
flight_766 = Flight.create(flight_number: 766, origin: 'CDG', destination: 'JFK', date: DateTime.new(2016,6,24), airplane_id: third_plane.id)
flight_877 = Flight.create(flight_number: 877, origin: 'HKG', destination: 'SYD', date: DateTime.new(2016,6,27), airplane_id: fourth_plane.id)
flight_988 = Flight.create(flight_number: 988, origin: 'SYD', destination: 'HKG', date: DateTime.new(2016,6,28), airplane_id: fourth_plane.id)
flight_112 = Flight.create(flight_number: 112, origin: 'SYD', destination: 'LAX', date: DateTime.new(2016,5,19), airplane_id: first_plane.id)
flight_223 = Flight.create(flight_number: 223, origin: 'LAX', destination: 'SYD', date: DateTime.new(2016,5,20), airplane_id: first_plane.id)
flight_334 = Flight.create(flight_number: 334, origin: 'LAX', destination: 'LHR', date: DateTime.new(2016,5,20), airplane_id: second_plane.id)
flight_445 = Flight.create(flight_number: 445, origin: 'LHR', destination: 'LAX', date: DateTime.new(2016,5,21), airplane_id: second_plane.id)
flight_556 = Flight.create(flight_number: 556, origin: 'JFK', destination: 'CDG', date: DateTime.new(2016,5,23), airplane_id: third_plane.id)
flight_667 = Flight.create(flight_number: 667, origin: 'CDG', destination: 'JFK', date: DateTime.new(2016,5,24), airplane_id: third_plane.id)
flight_778 = Flight.create(flight_number: 778, origin: 'HKG', destination: 'SYD', date: DateTime.new(2016,5,27), airplane_id: fourth_plane.id)
flight_889 = Flight.create(flight_number: 889, origin: 'SYD', destination: 'HKG', date: DateTime.new(2016,5,28), airplane_id: fourth_plane.id)

Reservation.destroy_all()
daniel111 = Reservation.create(user_id: daniel.id, flight_id: flight_111.id, seat_row: 3, seat_column: "A")
daniel222 = Reservation.create(user_id: daniel.id, flight_id: flight_222.id, seat_row: 8, seat_column: "C")
chris333 =  Reservation.create(user_id: chris.id, flight_id: flight_333.id, seat_row: 9, seat_column: "B")
chris444 =  Reservation.create(user_id: chris.id, flight_id: flight_444.id, seat_row: 10, seat_column: "A")
harrison555 =  Reservation.create(user_id: harrison.id, flight_id: flight_555.id, seat_row: 15, seat_column: "B")
harrison666 =  Reservation.create(user_id: harrison.id, flight_id: flight_666.id, seat_row: 10, seat_column: "C")
daniel111 = Reservation.create(user_id: daniel.id, flight_id: flight_111.id, seat_row: 4, seat_column: "B")
daniel222 = Reservation.create(user_id: daniel.id, flight_id: flight_222.id, seat_row: 9, seat_column: "D")
chris333 =  Reservation.create(user_id: chris.id, flight_id: flight_333.id, seat_row: 10, seat_column: "A")
chris444 =  Reservation.create(user_id: chris.id, flight_id: flight_444.id, seat_row: 11, seat_column: "C")
harrison555 =  Reservation.create(user_id: harrison.id, flight_id: flight_555.id, seat_row: 16, seat_column: "A")
harrison666 =  Reservation.create(user_id: harrison.id, flight_id: flight_666.id, seat_row: 11, seat_column: "D")
daniel111 = Reservation.create(user_id: daniel.id, flight_id: flight_111.id, seat_row: 5, seat_column: "D")
daniel222 = Reservation.create(user_id: daniel.id, flight_id: flight_222.id, seat_row: 10, seat_column: "B")
chris333 =  Reservation.create(user_id: chris.id, flight_id: flight_333.id, seat_row: 11, seat_column: "C")
chris444 =  Reservation.create(user_id: chris.id, flight_id: flight_444.id, seat_row: 12, seat_column: "D")
harrison555 =  Reservation.create(user_id: harrison.id, flight_id: flight_555.id, seat_row: 17, seat_column: "B")
harrison666 =  Reservation.create(user_id: harrison.id, flight_id: flight_666.id, seat_row: 12, seat_column: "A")
